const AUTH_ACTION_TYPES = {
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  REFRESH_AUTH_REQUEST: 'REFRESH_AUTH_REQUEST',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
  AUTH_REQUEST_ERROR: 'AUTH_REQUEST_ERROR',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
  LOGOUT_REQUEST_ERROR: 'LOGOUT_REQUEST_ERROR',
};

export default AUTH_ACTION_TYPES;